### ISSUE TITLE
Customizable zone colors

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#216]
Legit request from Brian Colligan
Related #215

**Comment by MrCsabaToth** [comment]
Other widgets:
* https://pub.dev/packages/flutter_hsvcolor_picker
* But the best looks like to be https://pub.dev/packages/flutter_circle_color_picker

**Comment by sebastiankutschbach** [comment]
In which part of the settings would you like it to see? In the Target HR or in the UX setting?

**Comment by MrCsabaToth** [comment]
> In which part of the settings would you like it to see? In the Target HR or in the UX setting?

I'm actively working on this right now. Zones color configuration will have a separate menu in the settings next to the other zone menus.
