### ISSUE TITLE
Schwinn 170 / 270 / 570u support

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#240]
Due to user complaints I discovered that Schwinn 170 and 270 were not FTMS machines.
Thanks to Kurt Ramsey there's an nRF Connect log about a Schwinn 270.
Seems like it's a proprietary characteristic 0x82a0 I need to reverse engineer.
[Schwinn.270.nRFConnect.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/7879988/Schwinn.270.nRFConnect.txt)
(Kurt's Ramsey's log)

**Comment by MrCsabaToth** [comment]
https://forums.zwift.com/t/help-needed-to-connect-schwinn-170-stationary-bike-with-zwift/374579/9

* https://github.com/ursoft/connectivity-samples/blob/08c4b415fa57da2b595cf195b695093615ec65d8/BluetoothLeGatt/Application/src/main/java/com/example/android/bluetoothlegatt/BluetoothLeService.java#L176
* https://forum.velomania.ru/showthread.php?t=282643&p=9070382&viewfull=1#post9070382

**Comment by MrCsabaToth** [comment]
https://github.com/ursoft/connectivity-samples/commit/da91a864a0ba2321aadc44d0ff01caf8c36d3594

**Comment by MrCsabaToth** [comment]
![sch170_1](https://user-images.githubusercontent.com/744949/168698680-134b968c-f4f4-48af-8172-712035bd135a.png)
![sch170_2](https://user-images.githubusercontent.com/744949/168698687-55e14533-4fec-4ba0-8795-b09bded84401.png)
![sch170_3](https://user-images.githubusercontent.com/744949/168698694-f621ae63-04bd-4fba-992c-521ac9b293b0.png)
![sch170_4](https://user-images.githubusercontent.com/744949/168698695-1d42f8df-8595-4e63-8675-1cc9c386b23a.png)
![sch170_5](https://user-images.githubusercontent.com/744949/168698701-1d2a84bb-2308-4f82-bef1-0dfc7c1c7c1f.png)

**Comment by MrCsabaToth** [comment]
Kooiboy's nRF Connect log of a Schwinn 570u:
[570 u Log 2022-05-17 18_55_24.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/8711252/570.u.Log.2022-05-17.18_55_24.txt)

**Comment by MrCsabaToth** [comment]
Source file: https://github.com/ursoft/connectivity-samples/blob/main/BluetoothLeGatt/Application/src/main/java/com/example/android/bluetoothlegatt/ChannelController.java

**Comment by MrCsabaToth** [comment]
Translated README:
> The Schwinn 570u protocol transformer (the product with the BTLE address 84:71:27:27:4A:44 is configured to connect automatically) to PowerMeter ANT + (40000) and Cadence Sensor ANT + (40001) - in this form Zwift already understands it. Simultaneously converted data is also issued via the BLE protocol. An analogue of this program for Windows (only the BLE protocol is implemented) - [https://github.com/ursoft/Jenx.Bluetooth.GattServer](https://github-com.translate.goog/ursoft/Jenx.Bluetooth.GattServer?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

Schwinn 570u protocol extracts

EventRecordDesc

    0509030100 - clicked start
    0509030300 - autopause?
    0509030000 - stop (here and above, the first 03 is the user number)

EventRecordDesc 3bf58980-3a2f-11e6-9011-0002a5d5c51b 5c7d82a0-9803-11e3-8a6c-0002a5d5c51b

    00 == 11 bytes?
    01 == 20
    02 == 00
    03 cyclic counter 00-20-40-60-80-a0-c0-e0
    04-06 LSB number of revolutions
    07? some kind of bit field, not a pulse!
    08-09 LSB number of 1024 seconds of training
    ten ? the smallest part of calories
    11-15 LSB some other counter, it grows faster under load - isn't it calories
    16 Difficulty level

"Power" is empirically "calculated" from calories.

Uncovered Topics:

    Where Schwinn 570u hides heart rate readings
    Is it possible to set the resistance level using commands via BTLE (judging by the identifiers in the protocol, no)

**Comment by MrCsabaToth** [comment]
[2605202213.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/8802381/2605202213.txt)
[3005202208.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/8802383/3005202208.txt)
[3005202220.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/8802385/3005202220.txt)
[3005202220_part2.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/8802388/3005202220_part2.txt)

**Comment by MrCsabaToth** [comment]
Test are flaky :(

**Comment by ursoft** [comment]
latest Schwinn 270 proto news - Heart Rate found: https://github.com/ursoft/ANT_Libraries/blob/e122c007f5e1935a9b11c05e601a71f2992bad45/ANT_DLL/WROOM_esp32/WROOM_esp32.ino#L866

**Comment by MrCsabaToth** [comment]
> latest Schwinn 270 proto news - Heart Rate found. Link to ESP-32 device (Schwinn270 BLE FTMS convertor) firmware: https://github.com/ursoft/ANT_Libraries/blob/e122c007f5e1935a9b11c05e601a71f2992bad45/ANT_DLL/WROOM_esp32/WROOM_esp32.ino#L866

Thanks so much for the heads up! I haven't looked at that file, I have so many questions, we need to talk.
1. So I need to attach to 0xb3c0 control characteristic and turn on the HR for this to work?
2. The 20 byte payload is not interfering with the 17 byte payload on the 0x82a0, but rather it's on a separate 0xf580 characteristic?
3. Is the https://github.com/ursoft/ANT_Libraries/blob/e122c007f5e1935a9b11c05e601a71f2992bad45/ANT_DLL/WROOM_esp32/WROOM_esp32.ino#L526 `coeffs` table serves a similar function as the https://github.com/ursoft/connectivity-samples/blob/da91a864a0ba2321aadc44d0ff01caf8c36d3594/BluetoothLeGatt/Application/src/main/java/com/example/android/bluetoothlegatt/BluetoothLeService.java#L202 `extra_mult`? I didn't understand why the conversion from the calories to the power is not linear, I guess the resistance curve is not linear? But then the calories wouldn't reflect that anyway? For me it was a challenge to calculate speed based on the power, not so long ago I applied a closed formula instead of a successive approximation (see the Cardano's Formula based formula at the bottom of https://www.gribble.org/cycling/power_v_speed.html)
4. Is there any engineering documentation or any kind of documentation about any of this from Schwinn?

**Comment by ursoft** [comment]
1. Yes. By default, the Schwinn is not send HR data even if Sdr0Char has subscriber. Here is the command to turn it on: https://github.com/ursoft/ANT_Libraries/blob/e122c007f5e1935a9b11c05e601a71f2992bad45/ANT_DLL/WROOM_esp32/WROOM_esp32.ino#L339
2. Yes, they don't interfere with each other.
3. `extra_mult` is 2nd algo, calculation by 'calories' and resistance with manual calibration - no power meter, only my feelings. Was very inaccurate (maybe, we got no calories at all in this field) - about 15% differ. `coeffs` is third algo (by resistance and cadence with power meter calibration). On the third iteration, I used the Favero Assioma Duo to calibrate each Schwinn resistance level at almost any cadence. I got about 5% of power accuracy, if you ignore the transients and flywheel inertia. As you can see, the all the functions is not always linear in my case. I do not know why.
4. No, Schwinn technical support pretends to be a valenki. And I could not get to their engineers.

**Comment by MrCsabaToth** [comment]
@ursoft Thanks for all your work, I included you in attributions for a while (https://trackmyindoorworkout.github.io/attributions/), let me know if I should link a concrete product or other name / link there. (Currently it's just the GitHub repo java file).

**Comment by ursoft** [comment]
BluetoothLeService.java is the oldest one, and will not be supported. The best is https://github.com/ursoft/ANT_Libraries/blob/master/ANT_DLL/WROOM_esp32/WROOM_esp32.ino

**Comment by MrCsabaToth** [comment]
@ursoft I have a question about the Schwinn 170 heart rate protocols. The `startHrStreamCmd[] = {0x5 /*len*/, 0x3 /*seq-с потолка*/, 0xd9 /*crc = sum to 0*/, 0, 0x1f /*cmd*/};` you send to the characteristic to turn the heart rate stream on: are the length, CRC bytes part of the lower level protocol stacks (GATT / ATT / L2CAP / ...) or when I'm all the way up at the application level I'd need to send these 5 bytes as they are? Meaning they are part of the Schwinn proprietary protocol? I guess so, because the BLE CRC is 3 bytes, but I want to be sure.

**Comment by ursoft** [comment]
> Meaning they are part of the Schwinn proprietary protocol?

Yes

**Comment by cagnulein** [comment]
hi @MrCsabaToth do you know if this bike can also have controlled resistance from bluetooth? An user from QZ reported me that it's possible via explore my world app. Are you aware of this?

**Comment by cagnulein** [comment]
Hah ok, yes I mean that qz, I'm the developer.
I hope you the best for your new job

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 18 ott 2024 alle 06:37 Csaba Toth ***@***.***>
ha scritto:

**Comment by MrCsabaToth** [comment]
> Hah ok, yes I mean that qz, I'm the developer.
> I hope you the best for your new job
> 
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud

Oh yes, awesome! Thanks for chiming in!
