### ISSUE TITLE
Add support for Yesoul S3

### ISSUE THREAD

**Issue by sebastiankutschbach** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#259]
The above mentioned device is recognized by the app but somehow there are now recordings shown when working out. I made a short log. Just ping me, if this is not sufficient or the wrong format (stuggling a bit with nrf connect and its log function).

[nRF Connect, 2022-03-04.txt](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/files/8184605/nRF.Connect.2022-03-04.txt)

**Comment by MrCsabaToth** [comment]
Sebastian reported it working
