### ISSUE TITLE
Strava login error on new installs

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#310]
Dan Walkes has a new install and the OAuth to Strava seems to be broken:
![Screenshot_20220629-221523](https://user-images.githubusercontent.com/744949/176595173-1fa397c3-7b5d-4441-a581-6db3fc46563a.png)

**Comment by MrCsabaToth** [comment]
It seems like the Strava OAuth is mingled with the Google OAuth, maybe somehow the dormant Google Fit integration merge interfered and broke the Strava (or other?) integrations?

**Comment by MrCsabaToth** [comment]
Ref https://github.com/flutter/flutter/issues/66721

**Comment by dwalkes** [comment]
Thanks @MrCsabaToth !
I just removed myself from the beta program, re-installed the non-beta and I on longer see this issue.  So it's either something specific to the beta or something about my previous install.

**Comment by MrCsabaToth** [comment]
Actually the Google Fit integration is still separated in a separate feature branch. I suspect that this is caused by breaking changes in `url_launcher`, namely that it is now working as in-app WebView, inside the Flutter sandbox. However I don't know how that leads to this Google OAuth messup/mixup, what a shitshow!

**Comment by MrCsabaToth** [comment]
Maybe the Google OAuth comes into play because Dan may use Google OAuth for logging in to Strava. So there's a chained OAuth going on: I kick off an OAuth for Strava and there's an OAuth within that for Google.

**Comment by MrCsabaToth** [comment]
I'll reopen until confirmed by Dan
