### ISSUE TITLE
Import [feature request]

### ISSUE THREAD

**Issue by ippocratis** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#518]
I paired the app with my ftms treadmill.
I just need a record of my runs.
Simple stats. Date, diatance, duration, pace.
I like the way the app displays the info and the stats are actually accurate.
I see there is integrations with strava etc but their starts at somehow inaccurate.
I also see there is fit,tcx and csv export.
What I can't find is a way to import those files back to the app.
It would be great if I could import/restore the exported workouts in case that the app is reinstalled etc

Thanks

**Comment by ippocratis** [comment]
Nevermind
Feature already there
Found it
Sorry

**Comment by MrCsabaToth** [comment]
No worries. I wish I had a documentation, it's planned but I don't have time for it right now.
