### ISSUE TITLE
Make the revolution sliding window configurable

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#538]
One of the PRs of #318 (https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/pull/494) decreases this from 5 to 3 for Schwinn only. Everywhere else it's 4. Probably we should make it configurable in the expert preferences.

**Comment by tkordenbrock** [comment]
This is great!  Thanks!

**Comment by MrCsabaToth** [comment]
I added the configuration at the bottom of the Expert section, right below the new sliding window configurations
